// `pnpm db:seed` — DB§21's deterministic dataset: 1 coach, 5 clients, 2
// programs, ~120 exercises, 4 weeks of realistic history, ~500 foods, 2
// form-check videos, 6 check-ins, weekly body metrics (CLAUDE.md §24).
//
// DETERMINISM CONTRACT — read this before adding an eleventh seed module.
// Three independent things must all stay fixed for two runs to produce
// byte-identical data, and every one of them is a real trap:
//
//   1. `faker.seed(42)` runs exactly once, right here, before any module
//      is called. Every module imports the shared instance from
//      `seed/lib/faker.ts`, never `@faker-js/faker` directly. Faker's RNG
//      is a single stream — the ORDER modules run in, and the order each
//      module calls faker internally, is part of the contract. Reordering
//      two modules below (even without touching what either generates)
//      shifts every faker call after that point and changes the entire
//      rest of the dataset. Don't reorder without a reason, and treat a
//      reorder as something the verification step (re-run + diff) must
//      re-prove.
//   2. Every row's `id` is generated by `seed/lib/deterministic-id.ts`'s
//      `seedId(key)` — a UUIDv5 hash of a fixed string — NEVER by the
//      schema's own `$defaultFn(uuidv7)` default, which embeds real
//      wall-clock time and would make every run's primary keys different.
//   3. Every "recent" date comes from `seed/lib/dates.ts`'s
//      `SEED_ANCHOR_DATE`, never `new Date()` — anchoring to the real
//      clock would make the dataset drift every day the script is run.
//   4. `created_at`/`updated_at` are set EXPLICITLY on every single insert,
//      never left to the column's own `.defaultNow()` — found live,
//      empirically, during this task's own verification: every table this
//      seed writes uses the shared `id`/`created_at`/`updated_at`
//      boilerplate (`_shared.ts`), and `.defaultNow()` is real wall-clock
//      time. Two runs a few seconds apart produced byte-identical data
//      everywhere else and silently different `created_at`/`updated_at`
//      on every row, in every table — the single largest source of
//      non-determinism in this file, and the easiest one to miss because
//      nothing about it looks wrong in isolation.
//
//      ONE narrow, understood, and permanent exception:
//      `training.workout_sessions.updated_at` on a *completed* session.
//      `recomputeSessionVolume` (training-history.ts) issues a real
//      `UPDATE` after the row's own `INSERT`, and `derived-data/01`'s
//      `touch_updated_at()` trigger — correctly, unconditionally, by
//      design (it has no bypass, unlike the guard triggers) — stamps that
//      `UPDATE` with real `now()`. There is no seed-side value that
//      survives a trigger doing its job; this is the trigger behaving
//      exactly as production needs it to. DB§21's determinism guarantee
//      therefore covers every column of every table this seed writes
//      EXCEPT this one column, on rows that went through the
//      recompute-after-insert pairing (`workout_sessions` rows for a
//      `skipped` session, which never calls `recomputeSessionVolume`, are
//      NOT affected and remain fully deterministic). Verified empirically:
//      a two-run diff of every other table, and every other column of this
//      one, is byte-identical.
//
// The whole seed runs inside ONE transaction: a failure partway through
// leaves no partial data, so re-running after a fix always starts from a
// genuinely empty database, never from a previous failed attempt's debris.
import { fileURLToPath } from 'node:url';

import { recomputeStorageUsage } from './aggregates/recompute-storage-usage.ts';
import { createDbClient } from './client.ts';
import { resolveConnectionString } from './migrate-env.ts';
import { seedBodyMetrics } from './seed/body-metrics.ts';
import { seedCheckins } from './seed/checkins.ts';
import { seedClients } from './seed/clients.ts';
import { seedCoach } from './seed/coach.ts';
import { seedExercises } from './seed/exercises.ts';
import type { SeededExercise } from './seed/exercises.ts';
import { seedFoods } from './seed/foods.ts';
import { seedFormChecks } from './seed/form-checks.ts';
import { faker } from './seed/lib/faker.ts';
import { seedNutritionHistory } from './seed/nutrition-history.ts';
import { seedAssignments, seedPrograms } from './seed/programs.ts';
import type { AssignmentDef } from './seed/programs.ts';
import { seedTrainingHistory } from './seed/training-history.ts';

// The four clients with 4 weeks of training + nutrition history — every
// client except the freshly `invited` one, who hasn't started yet.
const HISTORY_CLIENT_KEYS = ['client:1', 'client:2', 'client:4', 'client:5'];

const ASSIGNMENT_DEFS: AssignmentDef[] = [
  {
    clientKey: 'client:1',
    programKey: 'program:strength-8',
    currentWeek: 5,
    status: 'active',
    startDaysAgo: 32,
  },
  {
    clientKey: 'client:2',
    programKey: 'program:hypertrophy-12',
    currentWeek: 7,
    status: 'active',
    startDaysAgo: 46,
  },
  {
    clientKey: 'client:4',
    programKey: 'program:strength-8',
    currentWeek: 3,
    status: 'paused',
    startDaysAgo: 18,
  },
  {
    clientKey: 'client:5',
    programKey: 'program:hypertrophy-12',
    currentWeek: 4,
    status: 'cancelled',
    startDaysAgo: 25,
  },
];

function exerciseIdByName(exercises: SeededExercise[], name: string): string {
  const found = exercises.find((e) => e.name === name);
  if (!found) throw new Error(`seed.ts: no exercise named "${name}"`);
  return found.exerciseId;
}

async function seed(): Promise<void> {
  // Step 1 of the determinism contract — before ANY other faker call.
  faker.seed(42);

  const db = createDbClient({ connectionString: resolveConnectionString('local'), sslMode: false });

  try {
    const summary = await db.transaction(async (tx) => {
      // Fixed orchestration order — see the determinism contract above.
      const coach = await seedCoach(tx);
      const exercises = await seedExercises(tx);
      const exercisesByName = new Map(exercises.map((e) => [e.name, e]));
      const clients = await seedClients(tx, coach.coachProfileId);
      const clientIdByKey = new Map(clients.map((c) => [c.key, c.clientProfileId]));
      const clientUserIdByKey = new Map(clients.map((c) => [c.key, c.userId]));

      const programs = await seedPrograms(tx, coach.coachProfileId, exercisesByName);
      const assignments = await seedAssignments(
        tx,
        coach.coachProfileId,
        clientIdByKey,
        programs,
        ASSIGNMENT_DEFS,
      );
      const assignmentsByClientKey = new Map(assignments.map((a) => [a.clientKey, a]));

      const trainingHistory = await seedTrainingHistory(
        tx,
        coach.coachProfileId,
        clientIdByKey,
        assignmentsByClientKey,
      );

      const foods = await seedFoods(tx);
      const nutritionHistory = await seedNutritionHistory(
        tx,
        coach.coachProfileId,
        HISTORY_CLIENT_KEYS,
        clientIdByKey,
        foods,
      );

      const formChecks = await seedFormChecks(
        tx,
        coach.coachProfileId,
        coach.userId,
        clientIdByKey,
        clientUserIdByKey,
        [
          {
            key: 'maya-squat',
            clientKey: 'client:1',
            exerciseName: 'Barbell Back Squat',
            exerciseId: exerciseIdByName(exercises, 'Barbell Back Squat'),
          },
          {
            key: 'andre-deadlift',
            clientKey: 'client:2',
            exerciseName: 'Barbell Deadlift',
            exerciseId: exerciseIdByName(exercises, 'Barbell Deadlift'),
          },
        ],
      );

      // Every client's storage counter follows the same recompute-in-the-
      // same-transaction pairing training-history.ts and
      // nutrition-history.ts already exercise — one call per client whose
      // media_assets rows changed (the two form-check owners here).
      for (const clientKey of ['client:1', 'client:2']) {
        const userId = clientUserIdByKey.get(clientKey);
        if (userId) await recomputeStorageUsage(tx, userId);
      }

      await seedCheckins(tx, coach.coachProfileId, clientIdByKey);
      await seedBodyMetrics(tx, clientIdByKey);

      return {
        exercises: exercises.length,
        clients: clients.length,
        programs: programs.length,
        assignments: assignments.length,
        sessions: trainingHistory.sessionsCreated,
        setLogs: trainingHistory.setLogsCreated,
        foods: foods.length,
        meals: nutritionHistory.mealsCreated,
        mealItems: nutritionHistory.mealItemsCreated,
        formChecks: formChecks.length,
      };
    });

    console.log('[db:seed] done:', summary);
  } finally {
    await db.$client.end();
  }
}

const isMainModule = process.argv[1] === fileURLToPath(import.meta.url);
if (isMainModule) {
  seed().catch((error: unknown) => {
    console.error(error instanceof Error ? (error.stack ?? error.message) : error);
    process.exitCode = 1;
  });
}
