-- drizzle:non-transactional
-- A1/A9 (UNFORGET): DB§7's three named `workout_sessions` indexes and the
-- missing `media_assets.client_id` FK index. Generated by `db:generate`;
-- CONCURRENTLY added by hand per db-migrations §4/§6 and the 0031 precedent —
-- a plain build takes a SHARE lock and blocks every write to the table for
-- its duration, and `workout_sessions` is the product's hottest write path.
-- Additive only: nothing is dropped, altered or reordered.
CREATE INDEX CONCURRENTLY "sessions_client_date" ON "training"."workout_sessions" USING btree ("client_id","scheduled_date" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX CONCURRENTLY "sessions_coach_unreviewed" ON "training"."workout_sessions" USING btree ("coach_id","completed_at" DESC NULLS LAST) WHERE "training"."workout_sessions"."status" = 'completed' AND "training"."workout_sessions"."reviewed_at" IS NULL AND "training"."workout_sessions"."deleted_at" IS NULL;--> statement-breakpoint
CREATE INDEX CONCURRENTLY "sessions_coach_range" ON "training"."workout_sessions" USING btree ("coach_id","scheduled_date");--> statement-breakpoint
CREATE INDEX CONCURRENTLY "media_assets_client_id_idx" ON "coaching"."media_assets" USING btree ("client_id");
