// DB§8.1's own comment — "attached to every table with an updated_at
// column (generated by a migration helper)" — is an instruction to build
// tooling, not just a fact about the current state (derived-data/01).
//
// This script introspects the Drizzle schema barrel for every table
// carrying an `updated_at` column, then checks the target database for a
// `BEFORE UPDATE` trigger invoking `touch_updated_at()` on each one, and
// reports (non-zero exit) any gap. Wired into `db:generate`
// (package.json) so a table added in a later phase without the trigger
// is caught before merge, not discovered in production.
//
// Timing note: this checks the TARGET DATABASE's existing triggers, not
// the migration file `db:generate` just produced. A brand-new table with
// `updated_at` will correctly report as "missing" right after generation
// — that's the intended signal: hand-add its `CREATE TRIGGER` to the new
// migration (Drizzle can't do this itself), run `db:migrate`, then re-run
// this script to confirm it's covered.
import { is, sql } from 'drizzle-orm';
import { getTableConfig, PgTable } from 'drizzle-orm/pg-core';

import { createDbClient } from '../src/client.ts';
import { parseEnvironment, resolveConnectionString } from '../src/migrate-env.ts';
import * as schema from '../src/schema/index.ts';

type QualifiedTable = { schemaName: string; tableName: string };

function tablesWithUpdatedAt(): QualifiedTable[] {
  const found: QualifiedTable[] = [];
  for (const value of Object.values(schema)) {
    if (!is(value, PgTable)) continue;
    const config = getTableConfig(value);
    const hasUpdatedAt = config.columns.some((column) => column.name === 'updated_at');
    if (hasUpdatedAt) {
      found.push({ schemaName: config.schema ?? 'public', tableName: config.name });
    }
  }
  return found.sort((a, b) =>
    `${a.schemaName}.${a.tableName}`.localeCompare(`${b.schemaName}.${b.tableName}`),
  );
}

async function main(): Promise<void> {
  const target = parseEnvironment(process.env.DRIZZLE_ENV);
  const connectionString = resolveConnectionString(target);
  const db = createDbClient({
    connectionString,
    sslMode: target === 'local' ? false : 'require',
  });

  try {
    const expected = tablesWithUpdatedAt();
    console.log(`[list-updated-at-tables] ${expected.length} table(s) have an updated_at column.`);

    const rows = await db.execute<{ table_schema: string; table_name: string }>(sql`
      SELECT DISTINCT event_object_schema AS table_schema, event_object_table AS table_name
      FROM information_schema.triggers
      WHERE event_manipulation = 'UPDATE'
        AND action_statement ILIKE '%touch_updated_at%'
    `);
    const covered = new Set(rows.map((row) => `${row.table_schema}.${row.table_name}`));

    const missing = expected.filter((t) => !covered.has(`${t.schemaName}.${t.tableName}`));

    if (missing.length > 0) {
      console.error('[list-updated-at-tables] Missing touch_updated_at() trigger:');
      for (const t of missing) console.error(`  - ${t.schemaName}.${t.tableName}`);
      process.exitCode = 1;
    } else {
      console.log('[list-updated-at-tables] Every table with updated_at has the trigger attached.');
    }
  } finally {
    await db.$client.end();
  }
}

// Only ever invoked directly (package.json's db:generate wiring below) —
// no module-identity check needed, unlike migrate.ts which is also
// imported by other tooling.
main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
